### ISSUE TITLE
Why is year limited to 2099?

### ISSUE THREAD

**Issue by bmcdonnell** [Seeed-Studio/Seeed_Arduino_RTC#4]
Please consider either removing the limitation, or explaining the reason for it in the code comments.

If it is a hardware limitation, you might even consider changing the DateTime class to work with the actual year, and making the limitation part of the RTC classes. That would make DateTime more broadly useful.

**Comment by LynnL4** [comment]
Hi 
I'm not quite sure what problem you're talking about, you can set any year between 2000 and 2099, and this limit should be totally enough for the moment.

**Comment by bmcdonnell** [comment]
@LynnL4 @Pillar1989 it's conceivable that someone may want to use the code in a codebase that lives on for a while. 2099 is only 3 generations away. Unnecessarily small variables and limitations like this lead to rework like we had for Y2K.

Could you at least answer the titular question: *why* does this limit exist?

**Comment by LynnL4** [comment]
The vast bulk of RTC modules have this limitation, and I don't think that a simple rtc module should be considered for several generations of use.

**Comment by bmcdonnell** [comment]
@LynnL4 thanks.
