### ISSUE TITLE
[Feature] how about adding functions that return the time in the usual formats?

### ISSUE THREAD

**Issue by StefanL38** [Seeed-Studio/Seeed_Arduino_RTC#5]
Hi Seeeduino-Team,

I'm thankful that you coded a software RTC for SAMD21 in general.

But I want to post a feature requenst:
How about adding some functions or at least demo-codes that show how to the time-information is transformed into the usual formats like unix-time, epoc etc.?

Seeeduino is a microcontroller-board manufacturer. Providing good support for your boards IMHO seems to be a good investion. If I'm allowed to write an honest comment:

Seeeduino has very good tutorials that show all steps with screenshots etc.
With this library the quality level dropped towards the low end: a minimum of examples and that's all.
best regards Stefan

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

We will consider your request.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
