### ISSUE TITLE
__SAMD21__ guard

### ISSUE THREAD

**Issue by dpproto** [Seeed-Studio/Seeed_Arduino_RTC#6]
I'm using v2.0.0 of the library on a MKR WAN 1310. I couldn't compile a sketch (including the example) until I commented out the guard lines lines :
`#ifdef __SAMD21__`
in both the header files and the cpp files.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
